# Run `travis lint` when changing this file to avoid breaking the build.

cache:
  directories:
    - $HOME/.m2

services: docker

language: java

jdk: openjdk11

before_install:
  - echo checks.disable=true > ~/.testcontainers.properties
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "zipkinci"
  - git config user.email "zipkinci+zipkin-dev@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

# Override default travis to use the maven wrapper; skip license on travis due to #1512
install: ./mvnw install -Dlicense.skip=true -Dmaven.javadoc.skip=true -B -V

script: ./travis/publish.sh
# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ead3c37d57527214e9f2
      - https://webhooks.gitter.im/e/e57478303f87ecd7bffc
    on_success: change
    on_failure: always

env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "CXDhVmk9hLftNJ523o0MON1dE5SrpCUBjHKk28kWJXFhE31mvMlsn1+rek4I4nIBXfr7PfZlZNWDw4ezrHUZmGITVVQCZ2LO1f6F1i2NPSelT8wZ3bFV6otyYfUP8WgbVDiPOTnN+d6XCgTAZXMnwQBR/EQm8RhyxKvwmRGHj4Vk572osYS7VhIXgxnCdfUrQhhFEbWYvwk+3hvYjqtTwfwJwzSiSU29ouTFFB7sW6xYbp6VTrfs6sStrDbiuNt+XvB4+HIOVKJKC88+mXYKfbmtLPuBCL4/4WKISkAuXPOtEMmWU2xAz0iUYiheuVuvR4m32Caq0ReUPcX5lSWvXo2U8OdUGepQZoZyFMNygIOUfsuFUpcIE4+6k+HqjEn2ml4pDCIUIch2heBnAx3lntojUeEkzINpilNiJ9rPuwGWmR242JE9ke9/96LtDdfSKhd7+Ma2FWyntsCgQJUgfSVNFTSTgT34oW699cy5OHaB44Emgws4QzQDhZ1Habtom/wo7qpsSA3GC+c2sBOzMQv5NeIMbZ4So7bQySfBtcihfqwyxSfOVyhU6qIZlimMXFENpoGY4BPR1BOiKzqslACYA8dpZgTEaFhmfkNo8Gw8QAdNrd3H5MXAS2Pz1BONMreZLWXlxV5lj8KVo7SK2ifIUq77HetkdpcA38NjsfA="
    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
    - secure: "5GZeRg/agl3JB6j2xCgOHZbx9EhCMjncgQUpArsBz4oTYi9KwvoUQyIMRKy9KjJpdIT97yWSYOVx/jMsMWBLrMmvsTZ8hUyczDX9uRs1famKJwkidYKYpp6H76kKc3GRPdmV1EDEjdZV2YDX4xui6aAhxVizVNcfeRP30S6exCsKa2QIHbrLDyH+j6J5Byyx3eeY533xALwyPyQjv4/i6RTRMiURx8I2mi6/4SErgeOdwG+zRLhya0OzmkLv0FuCtK9AeyKegIVrMSi0v2rOOPXpGJyjP2xGp6HMXDMyOTV4uUDNoj2I25oW/d6YdJZ7N0my2S5ywe8afGZJdmasMz4nlSJnV8SEto6xk/ZlFNRy+hqaueGNcQl9TCMDWHfdBxPzr+4CAUN9kk3BjjapmEAiqyrL2SoI+ZBbXj5ZC+QiFRPWt9p6bQNeaw9CJ5JeuMavEO2hgKDyBYsiNuJOsmiIgfGcSgDTEaB31NyKv+6jK8uI6EFet/m2qXKYjwJuT3d5r71T+JkAS4O0wNelhGVUDdPmUkTKc98TeaMm+eVrPaS0i2j90m1S+I/PIKZpYqloKXh0ZAQJRuBEq+kgdNwL+bdNqszf6+ytoEjiNqWEqVOyPxDUs8b1zTUkNIWpGbXI1k2zQ/TzkJsDu1ME2UTd20lfz/EMm9hQUg7QsXk="
    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
    - secure: "AhI8jH8B82uul80geIvvOPuZJUABwveSI/o15WyetrtNctJA4rrPYCVTX95516DdCF7IDstFHT9hwhf7ISUGZYWpVPxd30gV+HbJoYiSI21Iby/0C4QisMCkUWCQkl7byZowchcxD+F+XnEwlBlqXCslsL65XcHXA0meYImLA0kzCs9ykCn23iOPz2TeMk9fSuUfI3vFPSdS8bVFaVth6c4yAfRk7SfnMQiZg5Ql6qYoe12FRkIC0UxpOnvZlY/qtcY7XaUJjIThK3h/qFWhMRGfi7NzWh7qUbICiBH1JNpCX8HK2j1QTaVc/Y19EzZQTZsGp5itGuqGEDWPaeSB/NH6YOZPwUE+zSL2ajFLzPeiIe2YU4lZMG9M5Ieo+3pXVbrRdVIU/YEkg/v9D+TzchioCLSOua30tNjiXV/iuECaiQ+v/KOVFOWau1T6Xqx0jWK4yksWCQ7ZuCRhjGcWpKku060i/c4I79KWtwbA4q5HOYAMX+EZRO4E4F2fPG20QVnfpyv7Du78pOj7ZHQn60DiobwUx/Cav3SJFZSjN6qmjYYjNrvYl3HUDOVNh2YzHTNuU1RT1kePZOkQ2PiPImQTOxaMm/tEqKOrjebVZDjjZdWHm/OabWl0coP+Ql7RBrzjXXxuqARUIVtKBwODXU9njMx1I3wJuxSIY2aeMDE="
    # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "nuEZ26Epjw/EcexIu4W579jtaJEZfV6vcNiSnaIzpuxrLRoEf7RfVWAmiRT3FdVR7LeAahBgyb7bkrw98qyt67jqyHUX1zWpnqWIQffdlVFBWfXiA22DBsfxMZ2FqRGyN4gTvEo2+Cw5seqvYrJ31LJexLmaQX0vtH4/tJWDRpW/zBWQ+aHOe8YWz5FpZpw+iHPsumRfKQGsQsWlXW1fEx7e/IT778K1y0bnjTkpbseFBaTe97fnWFB01+kWEsgeyY/pR3ZOrWDbMjqDMchLDAZQGLR/6zxAlEuSch6Y91MZzAURyN2j6YVkrwSVxuCxPDwI2BAI6QD5MK59F89k9W8gWojH+tTMslAvgKrqTqogkwGWQrqWwhgxCiJe9QY5IdArhu6PgZr9uDerU5TxQT/APZHbDkBb0aQlOvk1i3hbfclhnriCz2bLrg8T4ieKu1r2SkByy8OauiHXy4pj7y1LMRiqTKsoKr/pp5gOaMFkJNjqsPcRfGloez9N1uJuJQMV1+apvl3GLt6gDHsobcHGXp3JqI14emi7+WgpoBlteu+SQ1fnjp8EADtfa7SfPYJZ6HhgoPZfQOU+8okkfJA5y/qMVdIV1Lfmi0cAtaKCZ7nErZ9wGSHKp3MU31IFz4j+ta4s300YdE9gR3erbq8KsVTffPZ3x21a01dwHnU="
    # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "OcFeaA7aSbRn/udUCvRvdvQDFs9ZlA86NXv5EKFSI6mMfyL0Aa2FzbQE6Dar5RPTzCAi7nJvTq0x4RLn9Xi7g63G4jc/jFURjcy+Xjp2+227EDTrQhEnI4GcErRbnsoAfeDZmGCcSie1s6wTT57hfp5pIryy1ZnQkklqgjdFiW+C8X+KUdFD6y2L7Y8WT1fVOlHJf79tmy6lXL1btl2eFznd2mjlRZ3ELd6M+7B+PrikDjuRGjEYEDhEOBx07Og5SVMjvzzkLJeWr+jtWtQ0de2XgiMo034tFH9vjAUfAJi4HlReYxe4kWB21UW9zgjx7txuQU1Ci2HxKLNvRTA9FBVFaZMq9V/+lnxjRsMAjIBsBeFFobZrDWfxgz44042gdLW/9xD4KR7HdMUqoSBn/6Tr5kyDiA/XFWpouk6nvEoK3j3jagPWW0RyidfAtUWFDVv2NLzoLzt5ii2OnUvgHNLM4WNIzRIoOAE7jB7yLq0Evg2ZJ5Rl8KlSKrSkVgp9sLzeA8SwPoZbGQkSwrof9X+tG5EpLI8gqjUo8OyOy6ifqCDcL9fRHB+pcEjKtPP3ucK8alsk8pIsvmoYCU0tc0NTEqmfZOuovKSYjQuJpTxtayL8aobX5fjjt5Q7Z4iDUeKJJkuVi93VpF5SguF+b0TD8ApMLL7zmwlxkE5YzCM="

